import { PageTitle } from 'components/modules/page-title';

export const ProgramCSharpNameControlWinform = () => {
  return (
    <>
      <PageTitle title="Name Control In Winform"></PageTitle>
      <div className="row mt-2">
        <div className="col-12 col-sm-6 col-md-6">
          <table className="table table-striped table-hover table-bordered table-sm">
            <thead>
              <tr className="table-dark">
                <th>Tiền tố (prefix)</th>
                <th>Loại Control</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>lbl</td>
                <td>Label</td>
              </tr>
              <tr>
                <td>llbl</td>
                <td>LinkLabel</td>
              </tr>
              <tr>
                <td>btn</td>
                <td>Button</td>
              </tr>
              <tr>
                <td>txt</td>
                <td>Textbox</td>
              </tr>
              <tr>
                <td>mnu</td>
                <td>MainMenu</td>
              </tr>
              <tr>
                <td>chk</td>
                <td>CheckBox</td>
              </tr>
              <tr>
                <td>rdo</td>
                <td>RadioButton</td>
              </tr>
              <tr>
                <td>grp</td>
                <td>GroupBox</td>
              </tr>
              <tr>
                <td>pic</td>
                <td>PictureBox</td>
              </tr>
              <tr>
                <td>grd</td>
                <td>Grid</td>
              </tr>
              <tr>
                <td>lst</td>
                <td>ListBox</td>
              </tr>
              <tr>
                <td>cbo</td>
                <td>ComboBox</td>
              </tr>
              <tr>
                <td>lstv</td>
                <td>ListView</td>
              </tr>
              <tr>
                <td>tre</td>
                <td>TreeView</td>
              </tr>
              <tr>
                <td>tab</td>
                <td>TabControl</td>
              </tr>
              <tr>
                <td>dtm</td>
                <td>DateTimePicker</td>
              </tr>
              <tr>
                <td>mon</td>
                <td>MonthCalendar</td>
              </tr>
              <tr>
                <td>sbr</td>
                <td>ScrollBar</td>
              </tr>
              <tr>
                <td>tmr</td>
                <td>Timer</td>
              </tr>
              <tr>
                <td>spl</td>
                <td>Splitter</td>
              </tr>
              <tr>
                <td>dud</td>
                <td>DomainUpDown</td>
              </tr>
              <tr>
                <td>nud</td>
                <td>NumericUpDown</td>
              </tr>
              <tr>
                <td>trk</td>
                <td>TrackBar</td>
              </tr>
              <tr>
                <td>pro</td>
                <td>ProgressBar</td>
              </tr>
              <tr>
                <td>rtxt</td>
                <td>RichTextBox</td>
              </tr>
              <tr>
                <td>img</td>
                <td>ImageList</td>
              </tr>
              <tr>
                <td>hlp</td>
                <td>HelpProvider</td>
              </tr>
              <tr>
                <td>tip</td>
                <td>ToolTip</td>
              </tr>
              <tr>
                <td>cmnu</td>
                <td>ContextMenu</td>
              </tr>
              <tr>
                <td>tbr</td>
                <td>ToolBar</td>
              </tr>
              <tr>
                <td>frm</td>
                <td>Form</td>
              </tr>
              <tr>
                <td>bar</td>
                <td>StatusBar</td>
              </tr>
              <tr>
                <td>nico</td>
                <td>NotifyIcon</td>
              </tr>
              <tr>
                <td>ofd</td>
                <td>OpenFileDialog</td>
              </tr>
              <tr>
                <td>sdl</td>
                <td>SaveFileDialog</td>
              </tr>
              <tr>
                <td>fd</td>
                <td>FontDialog</td>
              </tr>
              <tr>
                <td>cd</td>
                <td>ColorDialog</td>
              </tr>
              <tr>
                <td>pd</td>
                <td>PrintDialog</td>
              </tr>
              <tr>
                <td>ppd</td>
                <td>PrintPreviewDialog</td>
              </tr>
              <tr>
                <td>ppc</td>
                <td>PrintPreviewControl</td>
              </tr>
              <tr>
                <td>err</td>
                <td>ErrorProvider</td>
              </tr>
              <tr>
                <td>pdoc</td>
                <td>PrintDocument</td>
              </tr>
              <tr>
                <td>psd</td>
                <td>PageSetupDialog</td>
              </tr>
              <tr>
                <td>crv</td>
                <td>CrystalReportDialog</td>
              </tr>
              <tr>
                <td>pd</td>
                <td>PrintDialog</td>
              </tr>
              <tr>
                <td>sw</td>
                <td>FileSystemWatcher</td>
              </tr>
              <tr>
                <td>log</td>
                <td>EventLog</td>
              </tr>
              <tr>
                <td>dire</td>
                <td>DirectoryEntry</td>
              </tr>
              <tr>
                <td>dirs</td>
                <td>DirectorySearcher</td>
              </tr>
              <tr>
                <td>msq</td>
                <td>MessageQueue</td>
              </tr>
              <tr>
                <td>pco</td>
                <td>PerformanceCounter</td>
              </tr>
              <tr>
                <td>pro</td>
                <td>Process</td>
              </tr>
              <tr>
                <td>ser</td>
                <td>ServiceController</td>
              </tr>
              <tr>
                <td>rpt</td>
                <td>ReportDocument</td>
              </tr>
              <tr>
                <td>ds</td>
                <td>DataSet</td>
              </tr>
              <tr>
                <td>olea</td>
                <td>OleDbDataAdapter</td>
              </tr>
              <tr>
                <td>olec</td>
                <td>OleDbConnection</td>
              </tr>
              <tr>
                <td>oled</td>
                <td>OleDbCommand</td>
              </tr>
              <tr>
                <td>sqla</td>
                <td>SqlDbDataAdapter</td>
              </tr>
              <tr>
                <td>sqlc</td>
                <td>SqlDbConnection</td>
              </tr>
              <tr>
                <td>sqld</td>
                <td>SqlDbCommand</td>
              </tr>
              <tr>
                <td>dvw</td>
                <td>DataView</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
};
