import unit1 from 'resources/json/japan/N5/Bai_1.json';
import unit2 from 'resources/json/japan/N5/Bai_2.json';
import unit3 from 'resources/json/japan/N5/Bai_3.json';
import unit4 from 'resources/json/japan/N5/Bai_4.json';
import unit5 from 'resources/json/japan/N5/Bai_5.json';
import unit6 from 'resources/json/japan/N5/Bai_6.json';
import unit7 from 'resources/json/japan/N5/Bai_7.json';
import unit8 from 'resources/json/japan/N5/Bai_8.json';
import unit9 from 'resources/json/japan/N5/Bai_9.json';
import unit10 from 'resources/json/japan/N5/Bai_10.json';
import unit11 from 'resources/json/japan/N5/Bai_11.json';
import unit12 from 'resources/json/japan/N5/Bai_12.json';
import unit13 from 'resources/json/japan/N5/Bai_13.json';
import unit14 from 'resources/json/japan/N5/Bai_14.json';
import unit15 from 'resources/json/japan/N5/Bai_15.json';
import unit16 from 'resources/json/japan/N5/Bai_16.json';
import unit17 from 'resources/json/japan/N5/Bai_17.json';
import unit18 from 'resources/json/japan/N5/Bai_18.json';
import unit19 from 'resources/json/japan/N5/Bai_19.json';
import unit20 from 'resources/json/japan/N5/Bai_20.json';
import unit21 from 'resources/json/japan/N5/Bai_21.json';
import unit22 from 'resources/json/japan/N5/Bai_22.json';
import unit23 from 'resources/json/japan/N5/Bai_23.json';
import unit24 from 'resources/json/japan/N5/Bai_24.json';
import unit25 from 'resources/json/japan/N5/Bai_25.json';

const dataN5 = new Map();
dataN5.set('unit_1', unit1);
dataN5.set('unit_2', unit2);
dataN5.set('unit_3', unit3);
dataN5.set('unit_4', unit4);
dataN5.set('unit_5', unit5);
dataN5.set('unit_6', unit6);
dataN5.set('unit_7', unit7);
dataN5.set('unit_8', unit8);
dataN5.set('unit_9', unit9);
dataN5.set('unit_10', unit10);
dataN5.set('unit_11', unit11);
dataN5.set('unit_12', unit12);
dataN5.set('unit_13', unit13);
dataN5.set('unit_14', unit14);
dataN5.set('unit_15', unit15);
dataN5.set('unit_16', unit16);
dataN5.set('unit_17', unit17);
dataN5.set('unit_18', unit18);
dataN5.set('unit_19', unit19);
dataN5.set('unit_20', unit20);
dataN5.set('unit_21', unit21);
dataN5.set('unit_22', unit22);
dataN5.set('unit_23', unit23);
dataN5.set('unit_24', unit24);
dataN5.set('unit_25', unit25);

export default dataN5;
