import { KanjiCategoryDto, KanjiDto } from './dto';
import { RADICALS } from './radicals';

export const KANJI_CATEGORIES: KanjiCategoryDto[] = [
  {
    id: 'radicals',
    name: 'Bộ thủ',
    description:
      'Toàn bộ 214 bộ thủ Khang Hy - nền tảng để nhận diện và tra cứu Kanji.',
  },
  {
    id: 'n5',
    name: 'Kanji JLPT N5',
    description: 'Danh sách Kanji cơ bản trong phạm vi kỳ thi JLPT N5.',
  },
  {
    id: 'n4',
    name: 'Kanji JLPT N4',
    description: 'Danh sách Kanji trong phạm vi kỳ thi JLPT N4.',
    disabled: true,
  },
];

const N5_KANJI: KanjiDto[] = [
  {
    kanji: '一',
    onyomi: 'イチ',
    kunyomi: 'ひと(つ)',
    hanViet: 'Nhất',
    meaning: 'Số một',
    example: '一つ (ひとつ) - một cái',
  },
  {
    kanji: '二',
    onyomi: 'ニ',
    kunyomi: 'ふた(つ)',
    hanViet: 'Nhị',
    meaning: 'Số hai',
    example: '二人 (ふたり) - hai người',
  },
  {
    kanji: '三',
    onyomi: 'サン',
    kunyomi: 'みっ(つ)',
    hanViet: 'Tam',
    meaning: 'Số ba',
    example: '三つ (みっつ) - ba cái',
  },
  {
    kanji: '四',
    onyomi: 'シ',
    kunyomi: 'よん・よ',
    hanViet: 'Tứ',
    meaning: 'Số bốn',
    example: '四月 (しがつ) - tháng Tư',
  },
  {
    kanji: '五',
    onyomi: 'ゴ',
    kunyomi: 'いつ(つ)',
    hanViet: 'Ngũ',
    meaning: 'Số năm',
    example: '五分 (ごふん) - năm phút',
  },
  {
    kanji: '六',
    onyomi: 'ロク',
    kunyomi: 'むっ(つ)',
    hanViet: 'Lục',
    meaning: 'Số sáu',
    example: '六月 (ろくがつ) - tháng Sáu',
  },
  {
    kanji: '七',
    onyomi: 'シチ',
    kunyomi: 'なな(つ)',
    hanViet: 'Thất',
    meaning: 'Số bảy',
    example: '七日 (なのか) - bảy ngày',
  },
  {
    kanji: '八',
    onyomi: 'ハチ',
    kunyomi: 'やっ(つ)',
    hanViet: 'Bát',
    meaning: 'Số tám',
    example: '八時 (はちじ) - 8 giờ',
  },
  {
    kanji: '九',
    onyomi: 'キュウ・ク',
    kunyomi: 'ここの(つ)',
    hanViet: 'Cửu',
    meaning: 'Số chín',
    example: '九月 (くがつ) - tháng Chín',
  },
  {
    kanji: '十',
    onyomi: 'ジュウ',
    kunyomi: 'とお',
    hanViet: 'Thập',
    meaning: 'Số mười',
    example: '十分 (じゅっぷん) - mười phút',
  },
  {
    kanji: '日',
    onyomi: 'ニチ・ジツ',
    kunyomi: 'ひ・か',
    hanViet: 'Nhật',
    meaning: 'Ngày, mặt trời',
    example: '日曜日 (にちようび) - Chủ nhật',
  },
  {
    kanji: '本',
    onyomi: 'ホン',
    kunyomi: 'もと',
    hanViet: 'Bản',
    meaning: 'Gốc, sách',
    example: '本 (ほん) - quyển sách',
  },
  {
    kanji: '人',
    onyomi: 'ジン・ニン',
    kunyomi: 'ひと',
    hanViet: 'Nhân',
    meaning: 'Người',
    example: '日本人 (にほんじん) - người Nhật',
  },
  {
    kanji: '中',
    onyomi: 'チュウ',
    kunyomi: 'なか',
    hanViet: 'Trung',
    meaning: 'Trung, giữa',
    example: '中国 (ちゅうごく) - Trung Quốc',
  },
  {
    kanji: '山',
    onyomi: 'サン',
    kunyomi: 'やま',
    hanViet: 'Sơn',
    meaning: 'Núi',
    example: '富士山 (ふじさん) - núi Phú Sĩ',
  },
  {
    kanji: '川',
    onyomi: 'セン',
    kunyomi: 'かわ',
    hanViet: 'Xuyên',
    meaning: 'Sông',
    example: '川 (かわ) - con sông',
  },
  {
    kanji: '田',
    onyomi: 'デン',
    kunyomi: 'た',
    hanViet: 'Điền',
    meaning: 'Ruộng',
    example: '田んぼ (たんぼ) - ruộng lúa',
  },
  {
    kanji: '目',
    onyomi: 'モク',
    kunyomi: 'め',
    hanViet: 'Mục',
    meaning: 'Mắt',
    example: '目 (め) - con mắt',
  },
  {
    kanji: '口',
    onyomi: 'コウ',
    kunyomi: 'くち',
    hanViet: 'Khẩu',
    meaning: 'Miệng',
    example: '入口 (いりぐち) - lối vào',
  },
  {
    kanji: '手',
    onyomi: 'シュ',
    kunyomi: 'て',
    hanViet: 'Thủ',
    meaning: 'Tay',
    example: '手紙 (てがみ) - lá thư',
  },
  {
    kanji: '足',
    onyomi: 'ソク',
    kunyomi: 'あし',
    hanViet: 'Túc',
    meaning: 'Chân',
    example: '足 (あし) - chân',
  },
  {
    kanji: '月',
    onyomi: 'ゲツ・ガツ',
    kunyomi: 'つき',
    hanViet: 'Nguyệt',
    meaning: 'Tháng, mặt trăng',
    example: '一月 (いちがつ) - tháng Một',
  },
  {
    kanji: '木',
    onyomi: 'モク・ボク',
    kunyomi: 'き',
    hanViet: 'Mộc',
    meaning: 'Cây',
    example: '木曜日 (もくようび) - thứ Năm',
  },
  {
    kanji: '水',
    onyomi: 'スイ',
    kunyomi: 'みず',
    hanViet: 'Thủy',
    meaning: 'Nước',
    example: '水曜日 (すいようび) - thứ Tư',
  },
  {
    kanji: '火',
    onyomi: 'カ',
    kunyomi: 'ひ',
    hanViet: 'Hỏa',
    meaning: 'Lửa',
    example: '火曜日 (かようび) - thứ Ba',
  },
  {
    kanji: '金',
    onyomi: 'キン',
    kunyomi: 'かね',
    hanViet: 'Kim',
    meaning: 'Vàng, tiền',
    example: '金曜日 (きんようび) - thứ Sáu',
  },
  {
    kanji: '土',
    onyomi: 'ド',
    kunyomi: 'つち',
    hanViet: 'Thổ',
    meaning: 'Đất',
    example: '土曜日 (どようび) - thứ Bảy',
  },
  {
    kanji: '上',
    onyomi: 'ジョウ',
    kunyomi: 'うえ',
    hanViet: 'Thượng',
    meaning: 'Trên',
    example: '上 (うえ) - phía trên',
  },
  {
    kanji: '下',
    onyomi: 'カ・ゲ',
    kunyomi: 'した',
    hanViet: 'Hạ',
    meaning: 'Dưới',
    example: '下 (した) - phía dưới',
  },
  {
    kanji: '大',
    onyomi: 'ダイ・タイ',
    kunyomi: 'おお(きい)',
    hanViet: 'Đại',
    meaning: 'To, lớn',
    example: '大学 (だいがく) - đại học',
  },
  {
    kanji: '小',
    onyomi: 'ショウ',
    kunyomi: 'ちい(さい)',
    hanViet: 'Tiểu',
    meaning: 'Nhỏ',
    example: '小学校 (しょうがっこう) - trường tiểu học',
  },
  {
    kanji: '女',
    onyomi: 'ジョ',
    kunyomi: 'おんな',
    hanViet: 'Nữ',
    meaning: 'Nữ',
    example: '女性 (じょせい) - phụ nữ',
  },
  {
    kanji: '男',
    onyomi: 'ダン',
    kunyomi: 'おとこ',
    hanViet: 'Nam',
    meaning: 'Nam',
    example: '男性 (だんせい) - đàn ông',
  },
  {
    kanji: '子',
    onyomi: 'シ',
    kunyomi: 'こ',
    hanViet: 'Tử',
    meaning: 'Con, trẻ em',
    example: '子供 (こども) - trẻ em',
  },
  {
    kanji: '学',
    onyomi: 'ガク',
    kunyomi: 'まな(ぶ)',
    hanViet: 'Học',
    meaning: 'Học',
    example: '学校 (がっこう) - trường học',
  },
  {
    kanji: '生',
    onyomi: 'セイ',
    kunyomi: 'い(きる)',
    hanViet: 'Sinh',
    meaning: 'Sinh, sống',
    example: '先生 (せんせい) - giáo viên',
  },
  {
    kanji: '先',
    onyomi: 'セン',
    kunyomi: 'さき',
    hanViet: 'Tiên',
    meaning: 'Trước',
    example: '先週 (せんしゅう) - tuần trước',
  },
  {
    kanji: '年',
    onyomi: 'ネン',
    kunyomi: 'とし',
    hanViet: 'Niên',
    meaning: 'Năm, tuổi',
    example: '今年 (ことし) - năm nay',
  },
  {
    kanji: '今',
    onyomi: 'コン',
    kunyomi: 'いま',
    hanViet: 'Kim',
    meaning: 'Bây giờ',
    example: '今日 (きょう) - hôm nay',
  },
  {
    kanji: '時',
    onyomi: 'ジ',
    kunyomi: 'とき',
    hanViet: 'Thời',
    meaning: 'Giờ, thời gian',
    example: '時間 (じかん) - thời gian',
  },
  {
    kanji: '分',
    onyomi: 'フン・ブン',
    kunyomi: 'わ(ける)',
    hanViet: 'Phân',
    meaning: 'Phút, chia',
    example: '三分 (さんぷん) - ba phút',
  },
  {
    kanji: '新',
    onyomi: 'シン',
    kunyomi: 'あたら(しい)',
    hanViet: 'Tân',
    meaning: 'Mới',
    example: '新聞 (しんぶん) - báo (tin mới)',
  },
].map((item, index) => ({
  ...item,
  id: index + 1,
  jlpt: 'N5' as const,
  categoryId: 'n5',
}));

export const KANJI_LIST: KanjiDto[] = [...N5_KANJI];

export function getKanjiByCategory(categoryId: string): KanjiDto[] {
  return KANJI_LIST.filter((item) => item.categoryId === categoryId);
}

export function getCategoryItemCount(categoryId: string): number {
  if (categoryId === 'radicals') return RADICALS.length;
  return getKanjiByCategory(categoryId).length;
}

export { RADICALS };
